# Generated by Django 3.1.7 on 2021-07-08 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210705_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper_order_history',
            name='order',
        ),
        migrations.AddField(
            model_name='shopkeeper_order_history',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
        migrations.AddField(
            model_name='shopkeeper_order_history',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='account.OrderItem'),
        ),
    ]
