# Generated by Django 3.1.7 on 2021-06-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer_shopkeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='Category',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
