# Generated by Django 3.1.7 on 2021-07-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210703_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.shopkeeper'),
        ),
    ]
